# Generated by Django 5.1.2 on 2024-10-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invantory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_product',
            field=models.BooleanField(default=False),
        ),
    ]
